services:
  # ----------------------------------------------------------------------------
  # DATABASE (PostgreSQL)
  # ----------------------------------------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: qa_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qa_infra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------------------------------------------------------
  # DB GUI (PgAdmin 4)
  # ----------------------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: qa_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - qa_infra
    depends_on:
      db:
        condition: service_healthy

  # ----------------------------------------------------------------------------
  # APP UNDER TEST (Local Instance)
  # ----------------------------------------------------------------------------
  app:
    build:
      context: ./vendor/restful-booker
      dockerfile: ../Dockerfile.booker
    container_name: qa_app_target
    restart: always
    ports:
      - "3001:3001"
    networks:
      - qa_infra

volumes:
  postgres_data:
  pgadmin_data:

networks:
  qa_infra:
    driver: bridge
